export const ROOMS = [
  {
    code: "SUN",
    name: "Pôr do Sol Casal",
    description: "Vista do pôr do sol, cidade, porto e mar. Cama casal.",
    size: 24,
    maxPax: 2,
    totalUhs: 46,
  },
  {
    code: "VMC",
    name: "Varanda Mar Casal",
    description: "Varanda privativa com vista privilegiada para o mar. Cama casal.",
    size: 26,
    maxPax: 2,
    totalUhs: 56,
  },
  {
    code: "VTC",
    name: "Varanda Triplo Casal +1",
    description: "Varanda privativa, 1 cama casal + 1 cama solteiro.",
    size: 26,
    maxPax: 3,
    totalUhs: 23,
  },
  {
    code: "VTT",
    name: "Varanda Triplo Twin",
    description: "Varanda privativa, 3 camas de solteiro.",
    size: 26,
    maxPax: 3,
    totalUhs: 8,
  },
  {
    code: "FRM",
    name: "Frente Mar Casal",
    description: "Vista privilegiada para o oceano. Cama king size.",
    size: 26,
    maxPax: 2,
    totalUhs: 36,
  },
  {
    code: "LAM",
    name: "Lateral Mar Casal",
    description: "Vista lateral para o mar. Cama casal.",
    size: 21,
    maxPax: 2,
    totalUhs: 16,
  },
  {
    code: "DOQ",
    name: "Double Queen",
    description: "Duas camas queen size. Ideal para famílias ou grupos.",
    size: 28,
    maxPax: 4,
    totalUhs: 16,
  },
  {
    code: "STC",
    name: "Standard Triplo Casal +1",
    description: "1 cama casal + 1 cama solteiro.",
    size: 24,
    maxPax: 3,
    totalUhs: 8,
  },
  {
    code: "SFM",
    name: "Suíte Frente Mar",
    description: "Suíte com vista espetacular para o mar. Poltrona de leitura.",
    size: 27,
    maxPax: 2,
    totalUhs: 8,
  },
  {
    code: "PAN",
    name: "Suíte Panorâmica",
    description: "Vista deslumbrante para a enseada de Pajuçara. Closet.",
    size: 30,
    maxPax: 2,
    totalUhs: 4,
  },
] as const

export const FB_SERVICES = [
  { id: "cafe_manha", label: "Café da Manhã", description: "Incluso na hospedagem" },
  { id: "almoco", label: "Almoço", description: "Restaurante principal ou Flor de Sal" },
  { id: "jantar", label: "Jantar", description: "Seg. à Sex das 19h às 22h" },
  { id: "coffee_break", label: "Coffee Break", description: "Para eventos e reuniões" },
  { id: "coquetel", label: "Coquetel / Welcome Drink", description: "Bar do Lobby ou Rooftop" },
  { id: "almoco_gala", label: "Almoço de Gala", description: "Flor de Sal (34 lugares)" },
  { id: "jantar_gala", label: "Jantar de Gala", description: "Flor de Sal (34 lugares)" },
] as const

export const CLIENT_TYPES = [
  "Empresa Privada",
  "Associação / Entidade",
  "Órgão Público / Governo",
  "Agência de Eventos",
  "Universidade / Instituição de Ensino",
  "Outro",
] as const

export const HOTEL = {
  name: "Sais Beach Living Hotel",
  address: "Av. Dr. Antônio Gouveia, 81 – Pajuçara, Maceió – AL, 57030-170",
  phone: "+55 82 3512-1004",
  website: "www.saishotel.com.br",
  emailGroups: "grupos.eventos@saishotel.com.br",
  emailReservas: "reservas@saishotel.com.br",
  pix: "33.265.094/0001-80",
  bankInfo: "Banco Itaú, Ag. 1598, CC: 39923-4",
  executive: "Bruna Barbosa",
  executiveTitle: "Analista de Grupos e Eventos",
} as const
