-- SAIS Beach Living Hotel — Groups & Events System
-- Run this in your Supabase SQL editor

create extension if not exists "uuid-ossp";

-- Leads (from client form at /grupos)
create table if not exists leads (
  id uuid primary key default uuid_generate_v4(),
  created_at timestamptz default now(),
  nome text not null,
  email text not null,
  telefone text not null,
  empresa text not null,
  tipo_cliente text not null,
  cargo text,
  nome_evento text not null,
  tipo_evento text,
  checkin date not null,
  checkout date not null,
  quartos jsonb not null default '{}',
  servicos_fb text[] not null default '{}',
  descricao_evento text,
  origem text,
  status text not null default 'novo'
    check (status in ('novo','em_contato','orcando','fechado','perdido')),
  rd_contact_id text,
  rd_deal_id text
);

-- Quotations (generated by executive)
create table if not exists quotations (
  id uuid primary key default uuid_generate_v4(),
  created_at timestamptz default now(),
  data_envio timestamptz,
  proposal_number text unique not null,
  lead_id uuid references leads(id) on delete set null,
  empresa text not null,
  tipo_cliente text not null,
  cliente text not null,
  email_cliente text not null,
  telefone_cliente text not null,
  nome_evento text not null,
  checkin date not null,
  checkout date not null,
  rooms jsonb not null default '[]',
  subtotal_bruto numeric(12,2) not null default 0,
  desconto_percentual numeric(5,2) not null default 0,
  valor_final numeric(12,2) not null default 0,
  composicao_hospedagem text,
  garantias text,
  validade integer not null default 7,
  observacoes text,
  codigo_promocional text,
  pdf_url text,
  trello_card_id text,
  rd_deal_id text,
  status text not null default 'rascunho'
    check (status in ('rascunho','enviado','aceito','recusado'))
);

-- Internal auth (single executive user, hashed password)
create table if not exists internal_users (
  id uuid primary key default uuid_generate_v4(),
  email text unique not null,
  password_hash text not null,
  created_at timestamptz default now()
);

-- RLS: disable for server-side access (use service role key in API routes)
alter table leads disable row level security;
alter table quotations disable row level security;
alter table internal_users disable row level security;
